// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/userpb/user.proto

package userpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserData struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbd27e4666d4e75a, []int{0}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UserData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegisterRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbd27e4666d4e75a, []int{1}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RegisterRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterRequest) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type RegisterResponse struct {
	Err                  int64     `protobuf:"varint,1,opt,name=Err,proto3" json:"Err,omitempty"`
	Msg                  string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *UserData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbd27e4666d4e75a, []int{2}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetErr() int64 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *RegisterResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RegisterResponse) GetData() *UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

type RetrieveRequest struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrieveRequest) Reset()         { *m = RetrieveRequest{} }
func (m *RetrieveRequest) String() string { return proto.CompactTextString(m) }
func (*RetrieveRequest) ProtoMessage()    {}
func (*RetrieveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbd27e4666d4e75a, []int{3}
}

func (m *RetrieveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveRequest.Unmarshal(m, b)
}
func (m *RetrieveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveRequest.Marshal(b, m, deterministic)
}
func (m *RetrieveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveRequest.Merge(m, src)
}
func (m *RetrieveRequest) XXX_Size() int {
	return xxx_messageInfo_RetrieveRequest.Size(m)
}
func (m *RetrieveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveRequest proto.InternalMessageInfo

func (m *RetrieveRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type RetrieveResponse struct {
	Err                  int64     `protobuf:"varint,1,opt,name=Err,proto3" json:"Err,omitempty"`
	Msg                  string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *UserData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RetrieveResponse) Reset()         { *m = RetrieveResponse{} }
func (m *RetrieveResponse) String() string { return proto.CompactTextString(m) }
func (*RetrieveResponse) ProtoMessage()    {}
func (*RetrieveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbd27e4666d4e75a, []int{4}
}

func (m *RetrieveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrieveResponse.Unmarshal(m, b)
}
func (m *RetrieveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrieveResponse.Marshal(b, m, deterministic)
}
func (m *RetrieveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrieveResponse.Merge(m, src)
}
func (m *RetrieveResponse) XXX_Size() int {
	return xxx_messageInfo_RetrieveResponse.Size(m)
}
func (m *RetrieveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrieveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrieveResponse proto.InternalMessageInfo

func (m *RetrieveResponse) GetErr() int64 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *RetrieveResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RetrieveResponse) GetData() *UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

type KvItem struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Val                  string   `protobuf:"bytes,2,opt,name=Val,proto3" json:"Val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KvItem) Reset()         { *m = KvItem{} }
func (m *KvItem) String() string { return proto.CompactTextString(m) }
func (*KvItem) ProtoMessage()    {}
func (*KvItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbd27e4666d4e75a, []int{5}
}

func (m *KvItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvItem.Unmarshal(m, b)
}
func (m *KvItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvItem.Marshal(b, m, deterministic)
}
func (m *KvItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvItem.Merge(m, src)
}
func (m *KvItem) XXX_Size() int {
	return xxx_messageInfo_KvItem.Size(m)
}
func (m *KvItem) XXX_DiscardUnknown() {
	xxx_messageInfo_KvItem.DiscardUnknown(m)
}

var xxx_messageInfo_KvItem proto.InternalMessageInfo

func (m *KvItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KvItem) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type ListRequest struct {
	Limit                int64     `protobuf:"varint,1,opt,name=Limit,proto3" json:"Limit,omitempty"`
	Offset               int64     `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Qs                   []*KvItem `protobuf:"bytes,3,rep,name=Qs,proto3" json:"Qs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbd27e4666d4e75a, []int{6}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetQs() []*KvItem {
	if m != nil {
		return m.Qs
	}
	return nil
}

type ListResponse struct {
	Err                  int64       `protobuf:"varint,1,opt,name=Err,proto3" json:"Err,omitempty"`
	Msg                  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 []*UserData `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbd27e4666d4e75a, []int{7}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetErr() int64 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *ListResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ListResponse) GetData() []*UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateRequest struct {
	Uid                  string    `protobuf:"bytes,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Data                 []*KvItem `protobuf:"bytes,2,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbd27e4666d4e75a, []int{8}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *UpdateRequest) GetData() []*KvItem {
	if m != nil {
		return m.Data
	}
	return nil
}

type UpdateResponse struct {
	Err                  int64     `protobuf:"varint,1,opt,name=Err,proto3" json:"Err,omitempty"`
	Msg                  string    `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data                 *UserData `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dbd27e4666d4e75a, []int{9}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetErr() int64 {
	if m != nil {
		return m.Err
	}
	return 0
}

func (m *UpdateResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *UpdateResponse) GetData() *UserData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*UserData)(nil), "userpb.UserData")
	proto.RegisterType((*RegisterRequest)(nil), "userpb.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "userpb.RegisterResponse")
	proto.RegisterType((*RetrieveRequest)(nil), "userpb.RetrieveRequest")
	proto.RegisterType((*RetrieveResponse)(nil), "userpb.RetrieveResponse")
	proto.RegisterType((*KvItem)(nil), "userpb.KvItem")
	proto.RegisterType((*ListRequest)(nil), "userpb.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "userpb.ListResponse")
	proto.RegisterType((*UpdateRequest)(nil), "userpb.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "userpb.UpdateResponse")
}

func init() { proto.RegisterFile("proto/userpb/user.proto", fileDescriptor_dbd27e4666d4e75a) }

var fileDescriptor_dbd27e4666d4e75a = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x8f, 0x12, 0x31,
	0x14, 0xc6, 0x61, 0x06, 0x27, 0xf8, 0x50, 0x24, 0x15, 0x61, 0xc2, 0xc1, 0x90, 0xea, 0x81, 0x83,
	0x41, 0x03, 0x27, 0x0f, 0xc6, 0x83, 0x70, 0x20, 0x10, 0x85, 0x31, 0x10, 0xa3, 0x5e, 0x8a, 0xf3,
	0x20, 0x93, 0x30, 0x32, 0xdb, 0x16, 0x08, 0xb7, 0xfd, 0xd3, 0x37, 0x6d, 0xa7, 0xec, 0xc0, 0x42,
	0xb2, 0xbb, 0xd9, 0x0b, 0xbc, 0x7e, 0x7d, 0xef, 0xd7, 0xef, 0xb5, 0x6f, 0xa0, 0x9e, 0xf0, 0xb5,
	0x5c, 0x7f, 0xdc, 0x08, 0xe4, 0xc9, 0x5c, 0xff, 0xb5, 0xb5, 0x42, 0x3c, 0x23, 0xd1, 0x4f, 0x50,
	0x9c, 0x0a, 0xe4, 0x3d, 0x26, 0x19, 0xa9, 0x80, 0x3b, 0x8d, 0x42, 0x3f, 0xdf, 0xcc, 0xb7, 0x9e,
	0x07, 0x2a, 0x24, 0x04, 0x0a, 0xdf, 0x59, 0x8c, 0xbe, 0xa3, 0x25, 0x1d, 0xd3, 0x01, 0xbc, 0x0a,
	0x70, 0x19, 0x09, 0x89, 0x3c, 0xc0, 0xab, 0x0d, 0x0a, 0x79, 0xbf, 0x42, 0x95, 0x35, 0xde, 0x85,
	0xbe, 0x6b, 0xb2, 0xc6, 0xbb, 0x90, 0xfe, 0x85, 0xca, 0x2d, 0x4a, 0x24, 0xeb, 0xff, 0x42, 0x67,
	0xf5, 0x39, 0xd7, 0x2c, 0x37, 0x50, 0xa1, 0x52, 0x62, 0xb1, 0x4c, 0x51, 0x2a, 0x24, 0xef, 0xa1,
	0x10, 0x32, 0xc9, 0x34, 0xaa, 0xd4, 0xa9, 0xb4, 0x4d, 0x2f, 0x6d, 0xdb, 0x48, 0xa0, 0x77, 0xe9,
	0x3b, 0x65, 0x54, 0xf2, 0x08, 0xb7, 0x78, 0xd1, 0xa8, 0xb1, 0x60, 0x93, 0x9e, 0xdc, 0xc2, 0x07,
	0xf0, 0x86, 0xdb, 0x81, 0xc4, 0x58, 0x11, 0x86, 0xb8, 0xb7, 0x27, 0x0f, 0x71, 0xaf, 0x94, 0x19,
	0x5b, 0x59, 0xe6, 0x8c, 0xad, 0xe8, 0x1f, 0x28, 0x8d, 0x22, 0x21, 0xad, 0xd9, 0x2a, 0x3c, 0x1b,
	0x45, 0x71, 0x24, 0x53, 0x23, 0x66, 0x41, 0x6a, 0xe0, 0xfd, 0x58, 0x2c, 0x04, 0x4a, 0x5d, 0xe9,
	0x06, 0xe9, 0x8a, 0xbc, 0x05, 0x67, 0x22, 0x7c, 0xb7, 0xe9, 0xb6, 0x4a, 0x9d, 0xb2, 0xb5, 0x63,
	0x0e, 0x0f, 0x9c, 0x89, 0xa0, 0xbf, 0xe0, 0x85, 0x81, 0x3f, 0xac, 0xc9, 0x9e, 0x69, 0xd2, 0x3d,
	0xdf, 0xa4, 0xfa, 0xa5, 0x7d, 0x78, 0x39, 0x4d, 0x42, 0x26, 0x2f, 0xdf, 0x32, 0xa1, 0x29, 0xc8,
	0x39, 0x6b, 0xcf, 0x60, 0x7e, 0x43, 0xd9, 0x62, 0x1e, 0x65, 0x31, 0x7f, 0xd9, 0x62, 0xe7, 0xda,
	0x81, 0xb2, 0x91, 0xc4, 0x4f, 0xe4, 0xdb, 0xe8, 0x1f, 0x92, 0x2f, 0xe0, 0x7d, 0xe3, 0xc8, 0x24,
	0x92, 0xba, 0x2d, 0x3a, 0x19, 0xeb, 0x86, 0x7f, 0x77, 0xc3, 0x38, 0xa3, 0x39, 0xf2, 0x15, 0x8a,
	0x76, 0x6e, 0xb2, 0x80, 0xa3, 0x71, 0xcb, 0x02, 0x8e, 0x47, 0x8c, 0xe6, 0x48, 0x17, 0x0a, 0xea,
	0x3d, 0xc8, 0x6b, 0x9b, 0x93, 0x79, 0xfa, 0x46, 0xf5, 0x58, 0x3c, 0x14, 0x7d, 0x06, 0xcf, 0xdc,
	0x11, 0x79, 0x73, 0xe8, 0x34, 0x7b, 0xf5, 0x8d, 0xda, 0xa9, 0x6c, 0x4b, 0xe7, 0x9e, 0xfe, 0xee,
	0xbb, 0x37, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x02, 0xed, 0x43, 0x12, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserDasServiceClient is the client API for UserDasService logic.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserDasServiceClient interface {
	//*
	// 创建用户
	Create(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	//*
	// 获取用户详情
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error)
	//*
	// 查询用户列表
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	//*
	// 更新用户
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
}

type userDasServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserDasServiceClient(cc *grpc.ClientConn) UserDasServiceClient {
	return &userDasServiceClient{cc}
}

func (c *userDasServiceClient) Create(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/userpb.UserDasService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDasServiceClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error) {
	out := new(RetrieveResponse)
	err := c.cc.Invoke(ctx, "/userpb.UserDasService/Retrieve", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDasServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/userpb.UserDasService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDasServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/userpb.UserDasService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDasServiceServer is the server API for UserDasService logic.
type UserDasServiceServer interface {
	//*
	// 创建用户
	Create(context.Context, *RegisterRequest) (*RegisterResponse, error)
	//*
	// 获取用户详情
	Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error)
	//*
	// 查询用户列表
	List(context.Context, *ListRequest) (*ListResponse, error)
	//*
	// 更新用户
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
}

// UnimplementedUserDasServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserDasServiceServer struct {
}

func (*UnimplementedUserDasServiceServer) Create(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUserDasServiceServer) Retrieve(ctx context.Context, req *RetrieveRequest) (*RetrieveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retrieve not implemented")
}
func (*UnimplementedUserDasServiceServer) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedUserDasServiceServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterUserDasServiceServer(s *grpc.Server, srv UserDasServiceServer) {
	s.RegisterService(&_UserDasService_serviceDesc, srv)
}

func _UserDasService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDasServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.UserDasService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDasServiceServer).Create(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDasService_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDasServiceServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.UserDasService/Retrieve",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDasServiceServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDasService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDasServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.UserDasService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDasServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDasService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDasServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userpb.UserDasService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDasServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserDasService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userpb.UserDasService",
	HandlerType: (*UserDasServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserDasService_Create_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _UserDasService_Retrieve_Handler,
		},
		{
			MethodName: "List",
			Handler:    _UserDasService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserDasService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/userpb/user.proto",
}
